# Server Configuration
server:
  port: ${PORT:0}

# Spring Configuration
spring:
  application:
    name: ms-bills
  # Database
  datasource:
    url: jdbc:h2:mem:bills_db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: ${SPRING_H2_USERNAME:sa}
    password: ${SPRING_H2_PASSWORD:sa}
  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
